version: "3.9"

services:
  db:
    image: postgres:15.1
    ports:
      - "5432:5432"
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    env_file:
      - .env
    command: celery -A settings.celery beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - db
      - rabbitmq
      - web
    restart: on-failure

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
      - web
    restart: on-failure

  web:
    build:
      context: .
      dockerfile: Dockerfile.news-service
    container_name: news-aggregator
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
