FROM python:3.11.8-slim

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["celery", "-A", "settings.celery", "worker", "--loglevel=info"]