# Generated by Django 5.0.6 on 2024-06-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=255, verbose_name="Keyword")),
                ("date", models.DateField(verbose_name="Date")),
            ],
            options={
                "unique_together": {("keyword", "date")},
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000, verbose_name="Title")),
                ("link", models.URLField(verbose_name="Article URL")),
                (
                    "publication_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publication Date"
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Sentiment Score"
                    ),
                ),
                (
                    "trends",
                    models.ManyToManyField(
                        related_name="news_articles", to="news.trend"
                    ),
                ),
            ],
            options={
                "verbose_name": "News article",
                "verbose_name_plural": "News articles",
            },
        ),
    ]
